# Generated by Django 3.2.12 on 2024-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0010_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
