# Generated by Django 3.2.12 on 2024-06-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0012_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresponse',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inte.user'),
            preserve_default=False,
        ),
    ]
