# Generated by Django 3.2.12 on 2024-06-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0014_delete_ocrresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
