# Generated by Django 5.0.3 on 2024-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0016_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='msgtxt',
            field=models.CharField(default='DEFAULT_MSG', max_length=255),
        ),
    ]
